### ISSUE TITLE
get form info on "continue" button click

### ISSUE THREAD

**Issue by hanayik** [hanayik/TemporalOrder#2]
- [x] make getSessionID function
- [x] make getTask function
- [x] make hideForm function (hint: change form-area style to display: none using JavaScript)

**Comment by KyleJP22** [comment]
Do you mean when writing the hidForm function it goes in the index HTML file not the app.js?

**Comment by hanayik** [comment]
@KyleJP22 No, you'll write it in the app.js file. BUT, you'll change the style attribute of the HTML using javascript. 

Hint (from google): 

`var form-area-div = document.getElementById('form-area');`
`form-area-div.style.display='none';`

**Comment by KyleJP22** [comment]
Ok that's what i thought
