### ISSUE TITLE
Make html element for task instructions

### ISSUE THREAD

**Issue by hanayik** [hanayik/TemporalOrder#4]
Task instructions will be different based on the value of the dropdown box. Add instructions using only JavaScript

Need instructions for:
- [x] Temporal order
- [x] Simuntaneity

**Comment by KyleJP22** [comment]
So far i have
function getTaskTypeID() {
  var taskID = document.getElementById('taskType').name;
  document.getElementById("taskType").innerHTML = taskID;

  if (value == 'to-bilateral') {
    return taskID.options[taskID.selectedIndex].text;
  }
  var text = getTaskTypeID('welcome to temp order bilateral')
}
Should i have this within the hideForm function so when it runs it completes all the functions and then brings up the text?
